version: "3.2"
services:
  footer:
    image: "nginx"
    ports:
      - "5000:80"
    volumes:
      - ./externalServices/footer:/usr/share/nginx/html:Z
  content:
    build: "./externalServices/content"
    ports:
      - "5001:6500"
    volumes:
      - ./externalServices/content:/usr/share/nginx/html
