version: "3.2"
services:
  footer:
    image: "nginx"
    ports:
      - "5000:80"
    volumes:
      - ./externalServices/footer:/usr/share/nginx/html:Z
  startpage_content:
    build: "./externalServices/startpage_content"
    ports:
      - "5001:6500"
  about_content:
    build: "./externalServices/about_content"
    ports:
      - "5002:6500"
  redis:
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
