/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { NewContentEventDetails } from "./utils/utils";
export namespace Components {
    interface MicroPuzzleAsyncElement {
    }
    interface MicroPuzzleElement {
        "name": string;
    }
    interface MicroPuzzleLoader {
        "streamRegisterName": string;
    }
}
declare global {
    interface HTMLMicroPuzzleAsyncElementElement extends Components.MicroPuzzleAsyncElement, HTMLStencilElement {
    }
    var HTMLMicroPuzzleAsyncElementElement: {
        prototype: HTMLMicroPuzzleAsyncElementElement;
        new (): HTMLMicroPuzzleAsyncElementElement;
    };
    interface HTMLMicroPuzzleElementElement extends Components.MicroPuzzleElement, HTMLStencilElement {
    }
    var HTMLMicroPuzzleElementElement: {
        prototype: HTMLMicroPuzzleElementElement;
        new (): HTMLMicroPuzzleElementElement;
    };
    interface HTMLMicroPuzzleLoaderElement extends Components.MicroPuzzleLoader, HTMLStencilElement {
    }
    var HTMLMicroPuzzleLoaderElement: {
        prototype: HTMLMicroPuzzleLoaderElement;
        new (): HTMLMicroPuzzleLoaderElement;
    };
    interface HTMLElementTagNameMap {
        "micro-puzzle-async-element": HTMLMicroPuzzleAsyncElementElement;
        "micro-puzzle-element": HTMLMicroPuzzleElementElement;
        "micro-puzzle-loader": HTMLMicroPuzzleLoaderElement;
    }
}
declare namespace LocalJSX {
    interface MicroPuzzleAsyncElement {
    }
    interface MicroPuzzleElement {
        "name"?: string;
    }
    interface MicroPuzzleLoader {
        "onNew-content"?: (event: CustomEvent<NewContentEventDetails>) => void;
        "streamRegisterName"?: string;
    }
    interface IntrinsicElements {
        "micro-puzzle-async-element": MicroPuzzleAsyncElement;
        "micro-puzzle-element": MicroPuzzleElement;
        "micro-puzzle-loader": MicroPuzzleLoader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "micro-puzzle-async-element": LocalJSX.MicroPuzzleAsyncElement & JSXBase.HTMLAttributes<HTMLMicroPuzzleAsyncElementElement>;
            "micro-puzzle-element": LocalJSX.MicroPuzzleElement & JSXBase.HTMLAttributes<HTMLMicroPuzzleElementElement>;
            "micro-puzzle-loader": LocalJSX.MicroPuzzleLoader & JSXBase.HTMLAttributes<HTMLMicroPuzzleLoaderElement>;
        }
    }
}
