global:
  footer:
    url: http://localhost:5000
  fallback:
    url: http://localhost:3300/loader.html
startpage:
  content:
    url: http://localhost:5001
  left:
    url: http://localhost:5003
about:
  content:
    url: http://localhost:5002
