version: "1"

definitions: 
  global:
    footer:
      url: http://footer
    header:  
      url: http://header
    fallback:
      url: http://localhost:3300/loader.html
  startpage:
    content:
      url: http://localhost:3000
      globalOverride: /src
  detail:
    content:
      url: http://detailpage

pages: 
  global: 
    fragments:
      header: global.header
      footer: global.footer
    template: ./index.html
  start: 
    url: "/"
    title: ""
    fragments: 
      content: startpage.content
  cart: 
    url: "/cart.html"
    title: "Cart"
    fragments: 
      content: cart.content
  about: 
    url: "/about.html"
    title: "about"
    fragments: 
      content: about.content