definitions: 
  global:
    footer:
      url: http://localhost:3331
    header:  
      url: http://localhost:3334 
    fallback:
      url: http://localhost:3300/loader.html
  startpage:
    content:
      url: http://localhost:3000
      globalOverride: /src
  detail:
    content:
      url: http://detailpage
  cart: 
    content: 
      url: http://localhost:3333

pages: 
  global: 
    fragments:
      header: global.header
      footer: global.footer
  start: 
    url: "/"
    title: ""
    fragments: 
      content: startpage.content
  cart: 
    url: "/cart.html"
    title: "Cart"
    fragments: 
      content: cart.content
    