global:
  footer:
    url: http://footer
  header: 
    url: http://header
  fallback:
    url: http://localhost:3300/loader.html
startpage:
  content:
    url: http://startpage
detail:
  content:
    url: http://detailpage
