version: "3.2"
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    mem_limit: 8M
    restart: on-failure
  redis:
    image: redis
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8089:8081"
  footer:
    build: "./footer"
  header:
    build: "./header"
  startpage:
    build: "./startpage"
  cart:
    build: "./cart"
  about: 
    build: "./about"
  detailpage:
    build: "./detailpage"
  micropuzzle:
    build: "./puzzle"
    ports:
      - "3300:3300" #Client port
      - "3301:3301" # Management port
    environment:
      - REDISADDR=redis:6379
      - MICROFRONTENDS=./config/frontends-dev.yaml
    volumes:
      - "./puzzle/config:/config"
